### ISSUE TITLE
Unlimited typed arguments

### ISSUE THREAD

**Issue by isaac-mason** [hmans/eventery#3]
I noticed that only 7 typed arguments are supported right now - I'm assuming because of limitations around type safety, and maybe because sane people wouldn't want more.

Regardless, unlimited type-safe arguments could be supported if the `Event` class had a single tuple generic. The usage would change slightly though.

e.g.
```ts
class Event<T extends Array<unknown>> {
  emit(...args: T): void {
    // ...
  }

  add(fn: (...args: T) => void): void {
    // ...
  }
}

new EventEmitter<[namedNumber: number, namedString: string]>()
```

---

Sorry if this isn't helpful at this point! Just keen to stop writing mini event emitters like these 😁

**Comment by hmans** [comment]
@isaac-mason Good to see you here \o/

As you've probably seen, this library isn't anywhere near finished; I'm still in the middle of making some basic design decisions like the one you've raised here.

There's a reason why the code is currently designed this way, and I'm trying to make up my mind if it's a _good_ reason that warrants this limitation (or not):

Most of the time, events with arguments will only ever have a single payload, which means they would need to be typed `Event<[number]>`. This somehow irked me. I know this is a pretty vain, superficial argument, which is why I'm not sure if I'll keep things that way.

Can arguments in tuples be named (like in your example)? Will these show up in argument hints in IDEs like VS Code? (I'm on the go at the moment, so I'd need to try later.) If this is the case (I was not aware of it), it would of course be a big argument in favor of that design.

**Comment by hmans** [comment]
Ha, I've successfully coffeeshop-experimented in TS Playground. That's really cool! Thanks for pushing me towards this. I'll go with this.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/1061/213209082-186542ec-7760-4251-8ce8-afe57740f180.png">

**Comment by hmans** [comment]
I've whipped up a quick PR, but will take another closer look at it & merge tomorrow:

https://github.com/hmans/eventery/pull/4

**Comment by isaac-mason** [comment]
Yeah! Sorry - forgot to mention. I made a codesandbox demonstrating that but forgot to include: https://codesandbox.io/s/tuple-generic-bqs2m3?file=/src/index.ts

If you want to get ultra fancy with typescript, maybe there's a way of supporting both the original syntax `Event<string, number>` up to however many generics, as well as a tuple generic `Event<[string, number]>`.

But maybe that's boiling the ocean 😅

**Comment by isaac-mason** [comment]
Ocean boiled, just for fun: https://codesandbox.io/s/tuple-generic-and-multiple-generics-3br8os?file=/src/index.ts

Using typescript conditionals, we can do both `new Event<string>()` and `new Event<[namedString: string]>()`.

This has one quirk though. If the type of the first argument is meant to be a tuple, e.g. `[string, number]`, you need to do `new Event<[[string, number]]>()`. I'd imagine that's a fairly edge case though.

**Comment by hmans** [comment]
This is now merged, thanks for the suggestion!

One of the advantages of having a single tuple type has always been that now there's at least the _possibility_ of adding more generic types in future upgrades to this library, so I don't think there's a need for mapped type trickery. With how this new change allows the user to name arguments (and even make them optional, or use rest arguments), this is clearly superior to the approach I was taking before.
